// <auto-generated />
namespace MeAnota.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ModeloInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModeloInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201211020416351_ModeloInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
